import { useState } from 'react';
import { AppShell } from '../../components/AppShell';
import { usePatientData } from '../../hooks/usePatientData';
import { weightChange, percentBodyWeightChange, formatDate } from '../../utils';
import { APP_CONFIG } from '../../config';
import { Printer, Copy, Calendar, Check } from 'lucide-react';

export function PatientReviewSummary() {
  const { patient, checkIns, medications, loading } = usePatientData();
  const [questions, setQuestions] = useState('');
  const [copied, setCopied] = useState(false);

  if (loading) {
    return (
      <AppShell role="patient" title="GP Review Summary" showBack>
        <div className="flex items-center justify-center py-20">
          <div className="w-8 h-8 border-2 border-[#1B3D34] border-t-transparent rounded-full animate-spin" />
        </div>
      </AppShell>
    );
  }

  if (!patient) return null;

  const medication = medications[0];
  const latestCheckIn = checkIns[checkIns.length - 1];
  const firstCheckIn = checkIns[0];

  const change = weightChange(patient.startingWeightKg, patient.currentWeightKg);
  const pct = percentBodyWeightChange(patient.startingWeightKg, patient.currentWeightKg);

  const dateRange = checkIns.length > 0
    ? `${formatDate(checkIns[0].date)} – ${formatDate(checkIns[checkIns.length - 1].date)}`
    : 'No check-ins recorded';

  const sideEffectCounts: Record<string, number> = {};
  checkIns.forEach(c => {
    c.sideEffects.filter(e => e !== 'none').forEach(e => {
      sideEffectCounts[e] = (sideEffectCounts[e] || 0) + 1;
    });
  });

  const avgAppetite = checkIns.length > 0
    ? (checkIns.reduce((s, c) => s + c.appetiteScore, 0) / checkIns.length).toFixed(1)
    : '—';

  const exerciseDays = checkIns.filter(c => c.exerciseLevel !== 'none').length;
  const proteinDays = checkIns.filter(c => c.proteinFocus).length;
  const hasRedFlag = checkIns.some(c => c.redFlag);

  const waistChange = firstCheckIn?.waistCm && latestCheckIn?.waistCm
    ? (latestCheckIn.waistCm - firstCheckIn.waistCm).toFixed(1)
    : null;

  const summaryText = `BETTERSTEP WEIGHT MANAGEMENT SUMMARY
Generated: ${new Date().toLocaleDateString('en-AU')}
Prepared by: ${APP_CONFIG.appName}

PATIENT: ${patient.name}
Date of Birth: ${patient.dateOfBirth}
Review Period: ${dateRange}

WEIGHT PROGRESS
Starting weight: ${patient.startingWeightKg} kg
Current weight: ${patient.currentWeightKg} kg
Total change: ${change > 0 ? '+' : ''}${change} kg (${parseFloat(pct) > 0 ? '+' : ''}${pct}% body weight)
Goal weight: ${patient.goalWeightKg} kg
${waistChange ? `Waist change: ${parseFloat(waistChange) > 0 ? '+' : ''}${waistChange} cm` : ''}

MEDICATION
${medication ? `${medication.name} ${medication.dose}\nStarted: ${medication.startDate}\nAdherence: Recorded in app\nTolerance notes: ${medication.toleranceNotes}` : 'No medication recorded'}

SIDE EFFECTS (${checkIns.length} check-ins)
${Object.keys(sideEffectCounts).length === 0 ? 'No side effects recorded' : Object.entries(sideEffectCounts).map(([k, v]) => `${k}: ${v} occasions`).join('\n')}
${hasRedFlag ? '\n⚠️ RED FLAG SYMPTOMS REPORTED — see details' : ''}

WELLBEING & LIFESTYLE
Average appetite score: ${avgAppetite}/10
Exercise days recorded: ${exerciseDays} of ${checkIns.length} check-ins
Protein focus days: ${proteinDays} of ${checkIns.length} check-ins

PATIENT QUESTIONS FOR GP REVIEW
${questions || 'None recorded'}

NEXT REVIEW
GP review due: ${formatDate(patient.nextReviewDate)}
${medication ? `Repeat prescription due: ${formatDate(medication.prescriptionReviewDate)}` : ''}

---
This summary was generated by BetterStep by Dr. Hewage.
It is intended to support GP review, not replace clinical assessment.
`;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <AppShell role="patient" title="GP Review Summary" showBack>
      <div className="space-y-5">
        {/* Header */}
        <div className="bg-gradient-to-br from-[#1B3D34] to-[#0F6D6D] rounded-2xl p-5 text-white">
          <p className="text-white/70 text-xs uppercase tracking-wide font-medium">Weight Management Summary</p>
          <h2 className="text-xl font-bold mt-1">{patient.name}</h2>
          <p className="text-white/80 text-sm mt-0.5">{dateRange}</p>
        </div>

        {checkIns.length === 0 && (
          <div className="bg-blue-50 border border-blue-100 rounded-2xl p-4">
            <p className="text-sm text-blue-700">Complete some check-ins to generate a full GP summary with trends and side-effect history.</p>
          </div>
        )}

        {/* Print area */}
        <div className="bg-white rounded-2xl border border-[#E7E5E1] shadow-sm overflow-hidden print-summary">
          <div className="p-5 space-y-4">
            {/* Weight */}
            <section>
              <h3 className="text-xs font-bold text-[#1B3D34] uppercase tracking-wide mb-3 border-b border-[#E7E5E1] pb-1">
                Weight Progress
              </h3>
              <div className="grid grid-cols-3 gap-3">
                <div className="text-center bg-[#F6F3EE] rounded-xl p-3">
                  <p className="text-xl font-bold text-[#1B3D34]">{patient.startingWeightKg}</p>
                  <p className="text-xs text-[#747B7D]">Starting (kg)</p>
                </div>
                <div className="text-center bg-[#F6F3EE] rounded-xl p-3">
                  <p className="text-xl font-bold text-[#1B3D34]">{patient.currentWeightKg}</p>
                  <p className="text-xs text-[#747B7D]">Current (kg)</p>
                </div>
                <div className={`text-center rounded-xl p-3 ${change < 0 ? 'bg-[#0F6D6D]/10' : 'bg-red-50'}`}>
                  <p className={`text-xl font-bold ${change < 0 ? 'text-[#0F6D6D]' : 'text-red-600'}`}>
                    {change > 0 ? '+' : ''}{change}
                  </p>
                  <p className="text-xs text-[#747B7D]">Change (kg)</p>
                </div>
              </div>
              <div className="mt-2 text-center">
                <span className={`text-sm font-semibold ${parseFloat(pct) < 0 ? 'text-[#0F6D6D]' : 'text-red-600'}`}>
                  {parseFloat(pct) > 0 ? '+' : ''}{pct}% body weight change
                </span>
              </div>
              {waistChange && (
                <p className="text-sm text-[#3C4346] mt-1 text-center">
                  Waist: {parseFloat(waistChange) > 0 ? '+' : ''}{waistChange} cm change
                </p>
              )}
            </section>

            {/* Medication */}
            {medication && (
              <section>
                <h3 className="text-xs font-bold text-[#1B3D34] uppercase tracking-wide mb-3 border-b border-[#E7E5E1] pb-1">
                  Medication
                </h3>
                <div className="text-sm space-y-1">
                  <div className="flex justify-between"><span className="text-[#3C4346]">Medication</span><span className="font-medium">{medication.name}</span></div>
                  <div className="flex justify-between"><span className="text-[#3C4346]">Current dose</span><span className="font-medium">{medication.dose}</span></div>
                  <div className="flex justify-between"><span className="text-[#3C4346]">Started</span><span className="font-medium">{formatDate(medication.startDate)}</span></div>
                  {medication.toleranceNotes && (
                    <div className="bg-[#F6F3EE] rounded-xl p-3 mt-2">
                      <p className="text-xs text-[#3C4346]">Tolerance notes: {medication.toleranceNotes}</p>
                    </div>
                  )}
                </div>
              </section>
            )}

            {/* Side effects */}
            <section>
              <h3 className="text-xs font-bold text-[#1B3D34] uppercase tracking-wide mb-3 border-b border-[#E7E5E1] pb-1">
                Side Effects ({checkIns.length} check-ins)
              </h3>
              {Object.keys(sideEffectCounts).length === 0 ? (
                <p className="text-sm text-[#3C4346]">No side effects recorded in this period.</p>
              ) : (
                <div className="space-y-1">
                  {Object.entries(sideEffectCounts).map(([effect, count]) => (
                    <div key={effect} className="flex justify-between text-sm">
                      <span className="capitalize text-[#3C4346]">{effect}</span>
                      <span className="font-medium">{count} occurrence{count !== 1 ? 's' : ''}</span>
                    </div>
                  ))}
                </div>
              )}
              {hasRedFlag && (
                <div className="mt-2 bg-red-50 border border-red-200 rounded-xl p-3">
                  <p className="text-xs font-semibold text-red-700">⚠ Red flag symptoms were reported during this period.</p>
                </div>
              )}
            </section>

            {/* Lifestyle */}
            <section>
              <h3 className="text-xs font-bold text-[#1B3D34] uppercase tracking-wide mb-3 border-b border-[#E7E5E1] pb-1">
                Wellbeing & Lifestyle
              </h3>
              <div className="text-sm space-y-1">
                <div className="flex justify-between"><span className="text-[#3C4346]">Average appetite score</span><span className="font-medium">{avgAppetite}/10</span></div>
                <div className="flex justify-between"><span className="text-[#3C4346]">Exercise days</span><span className="font-medium">{exerciseDays}/{checkIns.length}</span></div>
                <div className="flex justify-between"><span className="text-[#3C4346]">Protein focus days</span><span className="font-medium">{proteinDays}/{checkIns.length}</span></div>
              </div>
            </section>

            {/* Patient questions */}
            <section>
              <h3 className="text-xs font-bold text-[#1B3D34] uppercase tracking-wide mb-2 border-b border-[#E7E5E1] pb-1">
                My Questions for the GP
              </h3>
              <textarea
                className="w-full rounded-xl border border-[#E7E5E1] px-4 py-3 text-sm text-[#1B3D34] focus:outline-none focus:ring-2 focus:ring-[#1B3D34] resize-none"
                rows={3}
                placeholder="Write any questions you'd like to discuss with your GP..."
                value={questions}
                onChange={e => setQuestions(e.target.value)}
              />
            </section>

            {/* Next review */}
            <section>
              <h3 className="text-xs font-bold text-[#1B3D34] uppercase tracking-wide mb-3 border-b border-[#E7E5E1] pb-1">
                Next Steps
              </h3>
              <div className="text-sm space-y-1">
                <div className="flex justify-between"><span className="text-[#3C4346]">GP review due</span><span className="font-medium">{formatDate(patient.nextReviewDate)}</span></div>
                {medication && <div className="flex justify-between"><span className="text-[#3C4346]">Repeat prescription due</span><span className="font-medium">{formatDate(medication.prescriptionReviewDate)}</span></div>}
              </div>
            </section>
          </div>
        </div>

        {/* Actions */}
        <div className="grid grid-cols-3 gap-3">
          <button onClick={() => window.print()}
            className="flex flex-col items-center gap-1.5 bg-white border border-[#E7E5E1] rounded-2xl py-4 text-[#3C4346] hover:border-[#1B3D34] hover:text-[#1B3D34] shadow-sm">
            <Printer size={20} />
            <span className="text-xs font-medium">Print</span>
          </button>
          <button onClick={handleCopy}
            className={`flex flex-col items-center gap-1.5 rounded-2xl py-4 shadow-sm border ${copied ? 'bg-[#0F6D6D]/10 border-[#0F6D6D]/30 text-[#0F6D6D]' : 'bg-white border-[#E7E5E1] text-[#3C4346] hover:border-[#1B3D34] hover:text-[#1B3D34]'}`}>
            {copied ? <Check size={20} /> : <Copy size={20} />}
            <span className="text-xs font-medium">{copied ? 'Copied!' : 'Copy'}</span>
          </button>
          <a href={APP_CONFIG.bookingUrl} target="_blank" rel="noopener noreferrer"
            className="flex flex-col items-center gap-1.5 bg-[#1B3D34] rounded-2xl py-4 text-white shadow-sm">
            <Calendar size={20} />
            <span className="text-xs font-medium">Book</span>
          </a>
        </div>
      </div>
    </AppShell>
  );
}
